[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
didomi_program = "SNNuq33tepwjoqeRCj3GcNkW4R4hZF88pNMewZbxWyT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/muh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
