[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
didomi_program = "4f8xSv3wUdYUe2z343s4M2WRH7Hy2zr7Mdmpi31Y59bY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/muh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
